### ISSUE TITLE
facing with 'TypeError: getLanguageText(...) is undefined' error

### ISSUE THREAD

**Issue by ReyhaneMasumi** [Kiarash-Z/react-modern-calendar-datepicker#107]
Hi,
Your datepicker component worked well until 2days ago.
Suddenly our project stopped working with 'TypeError: getLanguageText(...) is undefined' error.
Also, We upgrade the module to ver 2.0 but the problem has not been resolved.
Please fix this bug ASAP cause this module is very good and efficient and we like to use it.
thanks.

**Comment by Kiarash-Z** [comment]
Hi, can you reproduce this issue on [getLanguageText](https://codesandbox.io/) please? this way, I can investigate the problem better 🙏🏻

**Comment by Kiarash-Z** [comment]
@ReyhaneMasumi  My guess is your error is because of the addition of the new `locale` prop in the new version which is breaking. You need to set `locale="fa"` in order to work with the module. [There are a couple of examples on the document.](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/different-locales)

**Comment by ReyhaneMasumi** [comment]
https://stackblitz.com/edit/react-5tq3uj?file=index.js
'utils' has bug!

**Comment by Kiarash-Z** [comment]
@ReyhaneMasumi yeah instead of `utils(true)` you had to use `utils('fa')`.
