### ISSUE TITLE
open/show class for datepicker

### ISSUE THREAD

**Issue by spostad7** [Kiarash-Z/react-modern-calendar-datepicker#120]
I want to add an opening animation for datepicker when the user clicks on input. It seems the '-calenderOpen' class is removed since the new release. how can I get opening datepicker status based on classNames?

**Comment by Kiarash-Z** [comment]
Hi @spostad7, you can actually look for an element with a class of `Calendar`. If there's such an element in DOM, the date picker is open. Otherwise, it's closed.

**Comment by spostad7** [comment]
@Kiarash-Z thank, but it is not possible for animating element that is not in DOM. if there is a class like 'open' that will add to the current element (e.g. .Datepicker), it is possible to animate it based on open class

**Comment by Kiarash-Z** [comment]
@spostad7 Can you explain your case a little more, please and why would you need such a class?

**Comment by spostad7** [comment]
@Kiarash-Z 
have a look at [emadseir datepicker](https://emadseir.net/fa) that designed with the previous version.
as u see I can handle opening animation (I mean with transform or opacity) with the open class when the calendar opens. as u know there is not such an action to animate elements if there are no elements in DOM

**Comment by Kiarash-Z** [comment]
@spostad7 That's a hell of customization. Great job! There's a way for achieving this in the latest version by:
1- Giving an initial animation style for the calendar like `opacity: 0; transform: translateY(2rem);`.
2- Listening for input `focus` & `blur` states to know when the date picker will be open/closed.
3- When date picker is open, Give the new animation style like `opacity: 1; transform: translateY(0)l`.

Step 2 can be a bit difficult because there are some exceptions for `blur` event where the calendar will be still open. If I add a minimal open/close animation to date picker for the future version, would it fit your use-case?

**Comment by spostad7** [comment]
@Kiarash-Z 
The problem still exists with the first approach because the element is not in DOM yet. here is my try for animating from none exist element to open state:
```
.DatePicker__calendarContainer {
    transform: translate3d(0, 5px, 0);
    opacity: 0;
    transition: transform 0.3s, opacity 0.3s;
}
.DatePicker__input:focus + .DatePicker__calendarContainer {
    opacity: 1;
    transform: translate3d(0,0,0);
}
```
also there is little point that after open datepicker, the two unwrapped element (.DatePicker__calendarContainer and .DatePicker__calendarArrow) will add seprately that is not suitable for animating and its better to wrap them in single parent tag.

The ideal approach is to add opening class to achieve such animation without js code, but I think your offer for adding minimal animation enough for this case :-)

**Comment by Kiarash-Z** [comment]
@spostad7 There's a minimal animation added when the calendar is opening in the latest version 3.1.0 🎉
