### ISSUE TITLE
header title

### ISSUE THREAD

**Issue by papinaser** [Kiarash-Z/react-modern-calendar-datepicker#127]
some time I want to show an title on header of calendar I want to do this feature

**Comment by Kiarash-Z** [comment]
Hi, can you explain the use cases for such a feature please?

**Comment by papinaser** [comment]
[image: image.png]

Like this page I want to add a feature that calendar have a label , I can
do this by change source in develop branch.

**Comment by thebrodmann** [comment]
> [image: image.png]

@papinaser we are not able to see any image!

**Comment by papinaser** [comment]
image for Kiarash
<https://drive.google.com/file/d/1ufhKPZrz0qV1p3Hd1K8LTh7V_8Th-D-_/view?usp=sharing>

@Kiarash-Z/react-modern-calendar-datepicker
<reply@reply.github.com>

**Comment by Kiarash-Z** [comment]
@papinaser Oh, I have to request access to just see an image? it would be nice if you could just copy-paste it here in Github. BTW, @thebrodmann is just really good! He can definitely help you 😊

**Comment by Kiarash-Z** [comment]
![image](https://user-images.githubusercontent.com/20098648/77531670-ec8a2f80-6eb0-11ea-93f2-cbcf91accd4e.png)

Ok here's the image. I think it would be much better if you move the title in input instead of the calendar. Input's placeholder is indeed better for such cases for accessibility and UX sakes.

**Comment by Kiarash-Z** [comment]
Closed due to inactivity.
