### ISSUE TITLE
Add `style` prop customization

### ISSUE THREAD

**Issue by LuisRizo** [Kiarash-Z/react-modern-calendar-datepicker#135]
**Is your feature request related to a problem? Please describe.**
In my company, we try to avoid adding CSS files as much as possible. Would it be possible to add a style prop rather than className props?

**Describe the solution you'd like**
The best solution would be to have an implementation similar to that of react-select (https://react-select.com/styles) that has a single `styles` prop that is an object that allows customizing every part of their components separately with CSS-in-JS styles.

**Describe alternatives you've considered**
Another alternative would be to have a similar prop that you do for className for every component (calendarClassName, calendarTodayClassName, calendarSelectedDayClassName, etc...) but for styles. Something like calendarStyle, calendarTodayStyle, calendarSelectedDayStyle, etc... that would take an object as the style.

Let me know your thoughts on this. I'd love to hear the reasoning behind using pure CSS styles vs CSS-in-JS.

**Comment by Kiarash-Z** [comment]
Hi, my reasons for using pure CSS over CSS-in-JS libraries are just similar to anyone who prefers them. [Here are a couple of reasons why:](https://medium.com/better-programming/using-css-modules-with-react-in-2020-73c2223f495c): 

- It’s just CSS
- No runtime
- Export styles to a CSS file easily
- Same setup for SSR and CSR

I don't find a `.js` file appropriate for writing styles there. I understand the idea behind CSS-in-JS libraries, but I don't find putting all your CSS styles in a JavaScript string. If we want to integrate our styles into our components, I would rather much more comprehensive approach like the one used in `Vue` in which you can easily specify your styles in your `Component.vue` by a `<styles></styles>` tag and, define your HTML structure in a `<template></template>` tag, and implement the logic in `<script></script>` tag. That's nice in `Vue` because the MVC structure of `Vue` lets you do that easily. However, `React` is not built of that structure. Therefore, we end up using CSS-in-JS libraries to have a similar compact component where everything about a component is in the component main file itself not noticing that `React` is not made for that. By the way, this is just my personal opinion.

**Comment by Kiarash-Z** [comment]
Closed due to inactivity.
