### ISSUE TITLE
Next/previous N day/month/year function

### ISSUE THREAD

**Issue by s-mahdi** [Kiarash-Z/react-modern-calendar-datepicker#155]
Hola!
I was working on `minimumDate` and set it up to `utils("fa").getToday` and everything was OK. unfortunately, the big BUG boss said: hmmm set `minimumDate` to tomorrow or n days/months/years after/before.
There is no such function in `utils` for this porpus. so I think some functions like so will bring heaven to us.
```typescript
const today = utils.getToday();
const value = {days: 10, months: 2, years: 4};
utils.getAfter(today, value);
utils.getBefore(today, value);
```
**Thanks in advance** :)

**Comment by s-mahdi** [comment]
Here is a function I created to get Tomorrow.
```typescript
const getTomorrow = () => {
  const date = utils("fa").getToday();

  if (date.day < utils("fa").getMonthLength(date)) {
    ++date.day;
  } else if (date.month < 12) {
    date.day = 1;
    ++date.month;
  } else {
    date.day = 1;
    date.month = 1;
    ++date.year;
  }

  return date;
};
```

**Comment by Kiarash-Z** [comment]
@s-mahdi Actually it's quite easy:

1- Get today using `utils('fa').getToday()`
2- Convert the above date to gregorian native date
3- Get the next day of the gregorian date
4- Convert the gregorian date to Jalaali date

Here's a sample: 

```js
const getTomorrow = () => {
  const todayJalaali = utils('fa').getToday();
  const todayGregorian = someFunctionToConvertToNativeDate(todayJalaali);
  todayGregorian.setDate(todayGregorian.getDate() + 1); // convert today to tomorrow!
  const tomorrowJalaali = someFunctionToConvertNativeDateToJalaali(todayGregorian);
  
  return tomorrowJalaali;
};
```

I'm not planning to export such functions for utilities. Because there will be more locales in the future(not limited to `'fa'` and `'en'`), and it's not a good practice to export a function to get tomorrow or any other specific day. This package is not a date utility library, It's merely a date picker. Of course, we provide some utilities, but due to the goal of this package, it would be irrelevant to provide more. Such actions should be achieved using a utility library such as `jalaali-js`(recommended) or `moment-jalaali`.

**Comment by s-mahdi** [comment]
Thanks, mate. going to close the issue.
