### ISSUE TITLE
<Datepicker/> showed inline when used inside material-ui modal

### ISSUE THREAD

**Issue by nimaa77** [Kiarash-Z/react-modern-calendar-datepicker#49]
**Describe the bug**
`<Datepicker/>` showed inline when used inside material-ui modal

**Reproduced Version on CodeSandbox**
Here it is on CodeSandBox: https://codesandbox.io/s/calendar-problem-1qe24?fontsize=14

**Expected behavior**
to not open inline

**Comment by thebrodmann** [comment]
Seems duplicate of #16

**Comment by Kiarash-Z** [comment]
Hi @nimaa77,

Actually, it gets opened, but because of the absolute positioning of the calendar. Modal wouldn't detect its boundaries and gets scrolled. There are two solutions to this:
1- Use `<Calendar />` instead of `<DatePicker />` in your modal.
2- Wrap the picker in a `div` element and give that `div` a `min-height`

If solutions are somehow vague to you, I can produce a working example on CodeSandbox

![Screen Shot 2019-10-26 at 1 23 44 PM](https://user-images.githubusercontent.com/20098648/67617827-fe798080-f7f3-11e9-86cb-ba3cb35eb8d7.jpg)

**Comment by nimaa77** [comment]
@Kiarash-Z hi bro,

I fixed this issue with one line of CSS:
```css
.overflowVisible {
  overflow: visible; 
}
```

and on `<Dialog>` just add that CSS class to paper styles:
```jsx
<Dialog classes={{ paper: "overflowVisible" }} >
```
and if Dialog content wrapped inside `<DialogContent>`:
```jsx
<DialogContent className="overflowVisible">
```

maybe it's better to add documentation for this.

**Comment by Kiarash-Z** [comment]
@nimaa77 It's not an issue with the date picker, so it's just a wrapper style affecting this
