### ISSUE TITLE
Animation speed

### ISSUE THREAD

**Issue by themzed** [Kiarash-Z/react-modern-calendar-datepicker#50]
**Is your feature request related to a problem? Please describe.**
Hi Kiarash, Thanks for awesome project. I feel animation on change month or year is a bit slow.

**Describe the solution you'd like**
If that's fine I can make a PR and fix this, then you can check it out and if that was fine merge it.

**Comment by Kiarash-Z** [comment]
Hi Mohammadreza,

There's no official prop available for changing the animation speed yet, but because I have used a CSS variable for animation speed, you can easily change it as below:
```
<Calendar calendarClassName="custom"/>
```
```
.custom {
  --animation-duration: 1s;
}
```

Here's a sample on [CodeSandbox](https://codesandbox.io/embed/new-hooks-gmi0e)
I think the animation duration is good for now. I would consider adding a prop for changing its value in later versions though. You can work on a `slideAnimationDuration` prop if you wish 😊

**Comment by themzed** [comment]
That's cool, I'll work on that. Thanks again.
