### ISSUE TITLE
Overlapping components

### ISSUE THREAD

**Issue by HosseinAlipour** [Kiarash-Z/react-modern-calendar-datepicker#53]
First off, thank you for this great project, it's awesome. I used it today and realized that other inputs of Datepickers overlap other Datepciker like this. I dunno if this is because of z-index or what. any ideas?
![Screenshot (61)](https://user-images.githubusercontent.com/5198502/67642088-8c9d5600-f91d-11e9-9abb-25debbd7bc8b.png)

**Comment by thebrodmann** [comment]
Hey @HosseinAlipour, can you provide a repro?

**Comment by Kiarash-Z** [comment]
Hi Hossein,
You can easily fix this problem by giving a custom className to date picker or calendar using `wrapperClassName` or `calendarClassName`(by overriding `z-index`)

**Comment by HosseinAlipour** [comment]
overriding z-index didn't help, I will provide a reproducible repo until night.

**Comment by Kiarash-Z** [comment]
@HosseinAlipour if possible, provide an example on [CodeSandbox](codesandbox.io)

**Comment by HosseinAlipour** [comment]
[here you go ](https://codesandbox.io/s/young-butterfly-x3ted)

**Comment by Kiarash-Z** [comment]
@HosseinAlipour as I told you, you can simply fix this by `wrapperClassName`: [Here's the SandBox 😊](https://codesandbox.io/embed/thirsty-galileo-kuui6)

**Comment by EleRam** [comment]
> @HosseinAlipour as I told you, you can simply fix this by `wrapperClassName`: [Here's the SandBox blush](https://codesandbox.io/embed/thirsty-galileo-kuui6)

I think it's better to set default z-index of ``.DatePicker__calendarContainer`` instead of wrapper.
default z-index of wrapper makes same problem on different situations

"از:" field is my custom `renderInput`
![Screenshot from 2020-09-19 11-52-21](https://user-images.githubusercontent.com/3352418/93661667-c663d780-fa6e-11ea-962e-ff246f3cd244.png)


and I fixed with this css:

```css
.DatePicker {
	z-index: initial !important;
}

.DatePicker__calendarContainer {
	z-index: 100;
}
```

![Screenshot from 2020-09-19 11-52-50](https://user-images.githubusercontent.com/3352418/93661664-c4017d80-fa6e-11ea-8006-66ddca229550.png)
