### ISSUE TITLE
Range DatePicker throws an error on `onChange` handler

### ISSUE THREAD

**Issue by thebrodmann** [Kiarash-Z/react-modern-calendar-datepicker#78]
**Describe the bug**
Range date picker throws an error on `onChange` handler. There is no issue with single day nor multiple days selector.

**Reproduced Version on CodeSandbox**
Here it is on [CodeSandBox](https://codesandbox.io/s/serene-fog-oob88-umf9h?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
It should run the `onChange` handler without throwing any exception.

**Comment by Kiarash-Z** [comment]
@thebrodmann First off, it seems that CodeSandbox isn't throwing the intended error. If you check this on your local machine it would throw an error like this:

![image](https://user-images.githubusercontent.com/20098648/70389622-41c03500-19d7-11ea-908c-461b5f2b570a.png)

That's because of the initial `value` of `{ from: undefined, to: undefined }` instead of `{ from: null, to: null }`, and why is that happening? because I deep clone `value` using `JSON.parse(JSON.stringify(obj))`, and interestingly, `JSON.stringify` will omit keys with the value of `undefined` when converting them to string, but if they have a value of `null` it will keep them. This behavior can be changed by changing `deepCloneObject` utility though, but I'm not quite sure for support for value `undefined` for range value keys instead of `null`.

**Comment by thebrodmann** [comment]
> I'm not quite sure for support for value undefined for range value keys instead of null.

It causes a breaking change. I think we should change the TypeScript type definition to just allow null type for range date selector.
I'm going to close this issue as it's intentional behavior.
Thank you.

**Comment by Kiarash-Z** [comment]
@thebrodmann have you checked v1.1.

**Comment by Kiarash-Z** [comment]
I merged your changes along with a fix to this issue
